"""DIMER inference package for the pinned ``google/deplot`` checkpoint."""

from .pipeline import (
    CELL_SEPARATOR,
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    INSTRUCTION,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MAX_PATCHES,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    RELATIVE_TOLERANCE,
    ROW_SEPARATOR,
    DePlotPipeline,
    cell_accuracy,
    cells_match,
    evaluation_report,
    header_font_bytes,
    parse_table,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "CELL_SEPARATOR",
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "INSTRUCTION",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MAX_PATCHES",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "RELATIVE_TOLERANCE",
    "ROW_SEPARATOR",
    "DePlotPipeline",
    "cell_accuracy",
    "cells_match",
    "evaluation_report",
    "header_font_bytes",
    "parse_table",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
