"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, metrics.py, samples.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E chart-to-table workflow: the pinned google/deplot snapshot is digest-verified
and loaded, one digest-pinned parquet shard of SynthChartNet charts is downloaded, converted to DePlot's own
table format, validated and split by chart type, a drawn bar chart is extracted through the inference contract,
the frozen model is scored on the held-out charts beside three non-neural baselines, a bounded fine-tuning of
the decoder's last blocks runs, the held-out split is scored again per chart type, the adapted model
re-extracts the drawn chart, and the adapter is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #6, DPC-M1..M3 / DPC-m1..m4): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); Sections 5-7 start from the pretrained model on every
re-run, Section 6 refuses an adapted model, `adapt` refuses an adapted pipeline and reload parity stops with an
explanation; the guided layer (audience, task contract, how to use, roadmap, glossary, predictions, worked answers,
a change-one-thing activity, troubleshooting, conclusion) is added and the setup cells are labelled Infrastructure;
the notebook states measured and estimated durations and prints progress during long stages; the BYOD contract
states and checks its real limits (12..2,502 records) before any model runs, takes a path as well as an upload and
names a missing records file; Section 8 reads the run's three deltas; and the charts themselves are shown.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "deplot_chart_pipeline",
    "repo_name": "deplot-chart-pipeline",
    "stem": "deplot_chart",
    "notebook_name": "deplot_chart_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`. The pins equal blip-captioning-pipeline's, so the
    # lock is that repository's (Colab T4 PASS at 2b8a77f), byte for byte.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `google/deplot` snapshot (a 1.13 GB `model.safetensors`), downloads one digest-pinned parquet shard of "
        "SynthChartNet charts from the Hugging Face Hub (516 MB, no credential, refused on any size or SHA-256 mismatch), "
        "converts each chart's OTSL table into DePlot's own linearised format, draws a seeded chart-type-stratified sample of "
        "360 training, 80 validation and 160 test charts with no image shared between splits, extracts the table of a drawn "
        "bar chart through the inference contract with an input manifest and a rejection probe, scores the frozen model on "
        "the test charts beside three non-neural baselines, runs a bounded fine-tuning of the decoder's last blocks with "
        "validation-cell-accuracy epoch selection, scores the held-out charts again per chart type, re-extracts the drawn "
        "chart with the adapted model, exports the adapter as safetensors with a manifest, and reloads that artifact into a "
        "fresh pipeline to verify table parity. The default path needs no repository clone, no DIMER worker or service, no "
        "credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used automatically "
        "when present, and a **GPU runtime is the recommended default**: the Kaggle Tesla T4 run of the previous notebook "
        "version (2026-09-26, same model stages, downloads included) took 4,794 s, about 80 minutes, of which the "
        "fine-tuning took 2,290 s. On CPU every chart is encoded at up to 2,048 patches and its table generated token by "
        "token: a local CPU measurement (24 threads) took about 7 s per extraction and 12 s per training step, so the "
        "default path is an estimated **2.4 hours or more** at 24 threads and **well over 5 hours** on a 2-vCPU hosted CPU "
        "runtime (lower-bound estimates, not runs). Building the isolated environment comes on top of these."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over into a *frozen* number). Supply one zip through the upload dialog on "
        "Colab, or a zip or folder path in `BYOD_PATH` on any runtime. It holds a `records.jsonl` (or `records.json`) of "
        "objects with `id`, `image` (a path relative to the records file; sub-folders such as `charts/c001.png` are kept), "
        "`target_text` (the chart's table in DePlot's linearised format: `TITLE | <title>` then rows joined by ` <0x0A> ` and "
        "cells by ` | `) and optional `image_id` and `chart_type`, beside the image files. It needs **12 to 2,502 records** "
        "(one per chart image): the split by image must leave at least 8 training, 2 validation and 2 test records, and at "
        "most 500 validation and 500 test records, the evaluation ceiling. Section 4 checks this before any model runs and "
        "names the split it refuses. A new upload replaces the previous one. The data passes through the same validation, "
        "seeded image-disjoint split, baselines, fine-tuning, held-out evaluation, artifact export and reload-parity cells "
        "as the SynthChartNet sample. The expected schema and the ceilings are stated in the Prerequisites and in "
        "Section 4, and uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "DePlotPipeline",
    "weights_key": "deplot",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "transformers"],
    "title": "DePlot — DIMER E2E chart-to-table fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/deplot-chart-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/deplot-chart-pipeline/blob/main/tutorials/deplot_chart_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-google%2Fdeplot-ffcc4d?style=flat",
            "https://huggingface.co/google/deplot",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-google--research%2Fpix2struct-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/google-research/pix2struct",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2212.10505-b31b1b.svg", "https://arxiv.org/abs/2212.10505"),
    ],
    "capability": "chart-to-table extraction and bounded supervised fine-tuning of the decoder's last blocks on a chart/table dataset, using the pinned `google/deplot` weights",
    "intro": (
        "`google/deplot` is the DePlot model of Liu et al. (2022) — a Pix2Struct image encoder over variable-resolution 16×16 "
        "patches (up to 2,048 per image) and a 12-layer text decoder, 282,285,696 parameters, fine-tuned by Google Research "
        "to translate a plot into its underlying data table — published under the **Apache-2.0** licence. The fixed "
        "instruction is **rendered as a text header above the chart** (the Pix2Struct convention, in Pillow's bundled font so "
        "no font is downloaded), the composite is encoded, and the decoder generates a linearised table with greedy decoding "
        "under a caller-owned `max_new_tokens` budget: a `TITLE | …` row, then rows joined by the literal token `<0x0A>` and "
        "cells by `|`. **No score exists**: the table is generated text with no probability and no correctness signal, and a "
        "well-formed table is **not evidence that its numbers** were read from the chart.\n\n"
        "What this notebook adds to inference is **adaptation with labelled tables**. The dataset is real chart/table pairs "
        "from a chart family DePlot was not fine-tuned on: SynthChartNet (docling-project), bar, pie, stacked-bar and line "
        "charts rendered with Matplotlib, Seaborn and Pyecharts from financial-report tables, published under the "
        "**CDLA-Permissive-2.0** licence. The notebook downloads **one pinned parquet shard** (516 MB, SHA-256 pinned in the "
        "carried module) and draws a seeded, chart-type-stratified subset from it. **Target format:** SynthChartNet stores "
        "each table as OTSL, with the axis categories of a bar, pie or stacked-bar chart along its first row; the frozen "
        "checkpoint, run on charts of this shard, writes one row per category instead (and a line chart's x points as rows, "
        "as OTSL already does), so the carried converter transposes bar, pie and stacked-bar tables, keeps line tables, and "
        "writes them in the model's own `TITLE |` / ` <0x0A> ` / ` | ` convention. The honest question is narrow: does a "
        "bounded adaptation of the decoder's last blocks on a few hundred charts of a new family move held-out cell accuracy "
        "at all, and on which chart type?\n\n"
        "Scores are **relaxed position-wise cell accuracy** (the repository's metric: every expected cell compared with the "
        "predicted cell at the same position, numbers within 5 %), **RNSS** (the relative number set similarity of the "
        "ChartQA and DePlot papers, which ignores layout) and exact-table match, overall and per chart type. Three references "
        "frame them: the **empty baseline**, the **header-only baseline** and the **medoid baseline** — systems that never "
        "look at the chart. Nothing here is a quality claim about your charts: it is one seeded split of one shard.\n\n"
        "**Weight-format note:** the pinned revision ships the model as SafeTensors (`model.safetensors`, digest-pinned in "
        "the manifest, loaded in float32); the processor is the VQA variant, which renders the header. Section 3 stages and "
        "digest-verifies the snapshot before the processor or the model is constructed.\n\n"
        "**Who this is for.** A learner who knows basic Python and PIL and has met the idea of an encoder–decoder model, and "
        "wants to see how a pretrained chart reader is measured against labelled tables and adapted to a new family of "
        "charts. No prior experience with DePlot, Pix2Struct, chart metrics or fine-tuning is assumed; each term is "
        "explained where it is first used and again in the **Glossary** at the end. A **GPU runtime** (for example a Colab "
        "or Kaggle T4) is recommended; CPU works but takes hours (Prerequisites).\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Extraction | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | one chart image (16 to 4096 px a side) and a token budget | 360 training charts, each with its table as a linearised target string |\n"
        "| Model | DePlot: the instruction rendered above the chart → Pix2Struct encoder (≤ 2,048 patches) → 12-layer text decoder, greedy decoding | the same model with the decoder's last 2 blocks and final layer norm trained, the rest frozen |\n"
        "| Output | the linearised table text, the parsed rows, a token count and a `truncated` flag — no score | an adapter (safetensors) and held-out cell accuracy / RNSS / exact-table match beside three baselines |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is much faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code and the model verification — and "
        "can be run without study; their code is collapsed. The learning path starts in Section 4. Form fields (`# @param`) "
        "are the only values meant to be edited; the defaults reproduce the recorded path. Each stage states what it does "
        "and asks you to **predict** before it runs, and the next cell opens with **What to notice** and a collapsible "
        "**Check your reasoning** block with a worked answer. Long stages print a progress line every 20 charts. Each "
        "optional experiment names the cell to change and the cells to re-run. Section 10 is a **change-one-thing "
        "activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your notes are "
        "optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, convert, validate and split the charts → 5 extract a drawn chart with the pretrained model → "
        "6 three baselines and the pretrained model on the test charts → 7 fine-tune the decoder's last blocks → 8 compare "
        "on the held-out charts → 9 re-extract, export and reload → 10 **change one thing: train one block instead of two** "
        "→ conclude. Core concepts are Sections 5 and 6 (what the model emits and how it is scored); evaluation practice is "
        "Sections 4, 7 and 8 (split, selection, held-out comparison); engineering and reproducibility are Sections 1–3 and 9."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *chart image → rendered instruction + patches → decoder → one "
        "linearised table* and say why the table carries no score (Section 5); (2) read relaxed cell accuracy and RNSS "
        "against three baselines that never see the chart, overall and per chart type, and say why a transposed table "
        "scores as a miss on every cell (Section 6); (3) explain how the validation split, never the test split, chooses "
        "the kept epoch (Section 7); (4) predict and then check whether cell accuracy and RNSS move together after a "
        "bounded fine-tuning, and diagnose a gain in layout from a gain in reading (Section 8); (5) check that an exported "
        "adapter reproduces the evaluated model (reload parity, Section 9); and (6) predict and then observe what training "
        "one decoder block instead of two changes (Section 10)."
    ),
    "exclusions": (
        "chart question answering or reasoning over the extracted table (the DePlot paper pairs the table with a language "
        "model; none is bundled), charts in images with several plots or a plot embedded in a page (one chart image per "
        "call), any instruction other than the fixed plot-to-table prompt, batch throughput, sampling or beam search, the "
        "DePlot paper's relative mapping similarity (RMS) and evaluation on ChartQA or PlotQA, fine-tuning of the image "
        "encoder, the embeddings or the output projection, training on charts that are not the pinned sample or your own "
        "uploads, and any claim that a SynthChartNet split stands in for your charts. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and PIL, and Colab or Jupyter familiarity; what an encoder–decoder model's generated tokens are; how a chart's data table is laid out (one row per category, one column per series). No prior experience with DePlot, chart metrics or fine-tuning: the notebook explains OTSL, the linearised table, rendered headers, cell accuracy, RNSS, the medoid baseline, teacher forcing and validation-based epoch selection where they are first used, and the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). A **GPU runtime is recommended**; the path runs on CPU too (float32) and uses CUDA automatically when available. Measured on the previous notebook version, whose model stages are the same: the Kaggle Tesla T4 run of 2026-09-26 took 4,794 s (about 80 minutes) including the downloads, of which fine-tuning took 2,290 s. On CPU, a local measurement (24 threads, files pre-staged) took about 7.3 s per extraction and 11.8 s per training step, and 27.2 s per extraction at 2 threads; the default path performs about 740 extractions and 270 training steps, so expect **at least 2.4 hours** at 24 threads and **well over 5 hours** on a 2-vCPU hosted CPU runtime (lower-bound estimates; no hosted CPU run is recorded). A free hosted session may end before a CPU run does. The locked install (PyTorch 2.14.0 with its CUDA libraries, a few GB), the 1.13 GB checkpoint and the 516 MB chart shard are the large downloads.",
        "- **Data contract:** records carry `id`, `image` and `target_text` — an image file decodable by Pillow with sides between `MIN_IMAGE_SIDE` (16) and `MAX_IMAGE_SIDE` (4096) px, and the chart's table as a DePlot linearised string of at most `MAX_TARGET_CHARS` (512) characters with at least one row; optional `image_id` groups related records on the same chart and optional `chart_type` labels the breakdown. Validation also hashes every image, so byte-identical files remain in one split even under different names or ids. Ids match `[A-Za-z0-9_.:-]` (1–64 characters) and are unique; every record on the same chart lands in the same split. The seeded split keeps about 20 % of the chart images for test and 15 % for validation, and must leave at least 8 training, 2 validation and 2 test records and at most 500 validation and 500 test records (`MAX_EVAL_RECORDS`, the evaluation ceiling), so a BYOD dataset needs **12 to 2,502 records** (one per chart image; the bounds shift when several records share a chart). Section 4 checks this before any model runs and names the split it refuses.",
        "- **BYOD layout:** one zip (by upload on Colab, or by path in `BYOD_PATH` on any runtime; a folder path also works) holding exactly one `records.jsonl` or `records.json` and the images, with each `image` given relative to the records file — sub-folders are kept as written. The zip may hold at most 20,000 members and expand to at most 2 GB; links and members that would land outside the upload folder are refused before anything is written. A new upload replaces the files of the previous one.",
        "- **Validation is structural, not semantic:** every image is opened and decoded and every target parsed, but nothing checks that a table is the chart's real data — a mislabelled chart is fine-tuned on without complaint, and SynthChartNet itself carries some label noise (for example a pie whose first category cell is a unit caption).",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path downloads one object from the Hub dataset repository `docling-project/SynthChartNet` at the immutable revision `b913ef98…` (`train-00000-of-00135.parquet`, 515,825,444 bytes) and refuses it unless its size and SHA-256 match the pins carried in `samples.py`; the chart images are written to the cache under their own content digest. SynthChartNet is published under CDLA-Permissive-2.0, which permits use and places no restriction on results such as trained weights; attribution to SynthChartNet (docling-project) is required when the data is shared.",
    ],
    "cells": [
        {
            "md": (
                "## 4. SynthChartNet charts, tables and split\n\n"
                "`fetch_corpus` returns the pinned shard from the cache under `weights/synthchartnet/` or downloads it at the "
                "pinned dataset revision, and refuses it unless its byte size and SHA-256 equal the pins in the carried module "
                "(it also refuses to run at all while no SHA-256 pin is recorded). This is the second large download (516 MB). "
                "`read_corpus` reads the table column with `pyarrow` and parses every **OTSL** table (the corpus's table markup: "
                "one token per cell, rows ended by a newline token). `build_sample_dataset` converts each table to its target with "
                "`target_from_otsl` — bar, pie and stacked-bar tables transposed to one row per category, line tables kept, "
                "`<ecel>` as an empty cell, `TITLE | ` first — leaves out the few charts whose target exceeds "
                "`MAX_TARGET_CHARS`, shuffles each chart type with `SPLIT_SEED`, and fills the test, validation and training "
                "splits to `SAMPLE_CHARTS` in proportion to the shard's type mix (so line charts, 0.5 % of the shard, get one "
                "or two charts per split, or none). A chart whose image digest was already drawn is skipped, so no image is "
                "shared between splits. `validate_dataset` then opens every image and parses every target, "
                "`check_split_disjoint` asserts no image is shared, and the training split is written to "
                "`outputs/{stem}_train.jsonl` in the shape BYOD expects. One training chart is shown beside its target table.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. The cell empties `work/byod/` first, so a second upload never reads the first one's files; it "
                "refuses a zip with more than 20,000 members, more than 2 GB expanded, a link or a member that would land outside "
                "`work/byod/`, before writing anything; it keeps sub-folders, so `image` paths are read relative to the records "
                "file; and an empty or cancelled upload, a zip without `records.jsonl` / `records.json`, or a non-Colab runtime "
                "without `BYOD_PATH` stops with a message saying what to supply. `split_dataset` then makes a seeded 65 / 15 / "
                "20 % split **by chart image** and refuses a dataset that leaves fewer than 8 training, 2 validation or 2 test "
                "records, or more than 500 validation or test records, naming the split (12 to 2,502 records, one per chart). "
                "Under BYOD the printed provenance and `result.json` describe your upload, not the SynthChartNet corpus.\n\n"
                "Look for: the shard's row count and type mix, one raw OTSL table beside its converted target, the chart "
                "counts per split and per type, the table shapes, three digests, and four refusal probes — a duplicate id, a "
                "missing image file, a target with no table row and a dataset too small to split — each rejected before "
                "`torch` does anything.\n\n"
                "**Predict before running:** line charts are about 0.5 % of the shard. How many line charts will the 160 test "
                "charts hold — and what does that mean for a per-chart-type score on line charts?"
            ),
            "code": (
                "import collections\n"
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "import shutil\n"
                "import stat\n"
                "import zipfile\n\n"
                "from PIL import Image\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "MAX_ZIP_MEMBERS = 20_000\n"
                "MAX_ZIP_BYTES = 2_000_000_000\n"
                "RECORDS_NAMES = ('records.jsonl', 'records.json')\n\n\n"
                "def show_chart(source, width=480):\n"
                "    \"\"\"Display a chart (an image or a path) scaled to at most `width` px wide.\"\"\"\n"
                "    chart = source.copy() if isinstance(source, Image.Image) else Image.open(source)\n"
                "    chart = chart.convert('RGB')\n"
                "    chart.thumbnail((width, width * 4))\n"
                "    display(chart)\n\n\n"
                "def show_table(label, text, limit=6):\n"
                "    \"\"\"Print a linearised table one row per line (at most `limit` rows), so it can be read beside its chart.\"\"\"\n"
                "    rows = [row.strip() for row in str(text).split(ROW_SEPARATOR)]\n"
                "    print(f'{{label}}:')\n"
                "    for row in rows[:limit]:\n"
                "        print('    ' + row)\n"
                "    if len(rows) > limit:\n"
                "        print(f'    ... {{len(rows) - limit}} more rows')\n\n\n"
                "def extract_zip(payload, root, label):\n"
                "    \"\"\"Extract an uploaded zip under root, keeping sub-folders and refusing the whole archive before writing anything unsafe.\"\"\"\n"
                "    base = root.resolve()\n"
                "    try:\n"
                "        archive = zipfile.ZipFile(io.BytesIO(payload))\n"
                "    except zipfile.BadZipFile:\n"
                "        raise ValueError(f'{{label}} is not a readable zip file: zip the records file and the images together and supply that zip.') from None\n"
                "    with archive:\n"
                "        members = archive.infolist()\n"
                "        expanded = sum(m.file_size for m in members)\n"
                "        if len(members) > MAX_ZIP_MEMBERS or expanded > MAX_ZIP_BYTES:\n"
                "            raise ValueError(f'{{label}} holds {{len(members)}} members and expands to {{expanded}} bytes; the limits are {{MAX_ZIP_MEMBERS}} members and {{MAX_ZIP_BYTES}} bytes, checked before anything is written.')\n"
                "        for member in members:\n"
                "            if stat.S_ISLNK(member.external_attr >> 16):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} is a symbolic link, which is not accepted; nothing was extracted.')\n"
                "            target = (root / member.filename).resolve()\n"
                "            if target == base or not target.is_relative_to(base):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} would land outside the upload folder; nothing was extracted.')\n"
                "        for member in members:\n"
                "            if not member.is_dir():\n"
                "                target = (root / member.filename).resolve()\n"
                "                target.parent.mkdir(parents=True, exist_ok=True)\n"
                "                target.write_bytes(archive.read(member))\n\n\n"
                "def find_records_file(root, label):\n"
                "    found = sorted(p for p in Path(root).rglob('*') if p.name in RECORDS_NAMES and '__MACOSX' not in p.parts)\n"
                "    if not found:\n"
                "        raise ValueError(f'No records.jsonl or records.json found in {{label}}. Put one records file of {{{{id, image, target_text}}}} objects beside the images (image paths relative to it), then run this cell again.')\n"
                "    if len(found) > 1:\n"
                "        raise ValueError(f'{{label}} holds more than one records file; keep exactly one of: ' + ', '.join(str(p.relative_to(root)) for p in found))\n"
                "    return found[0]\n\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    byod_root = Path('work') / 'byod'\n"
                "    if byod_root.exists():\n"
                "        shutil.rmtree(byod_root)  # a new upload never reads files left by an earlier one\n"
                "    byod_root.mkdir(parents=True)\n"
                "    payload = None\n"
                "    if BYOD_PATH.strip():\n"
                "        source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name = source.name\n"
                "        if source.is_dir():\n"
                "            records_file = find_records_file(source, str(source))\n"
                "        elif source.suffix.lower() == '.zip':\n"
                "            payload = source.read_bytes()\n"
                "            extract_zip(payload, byod_root, file_name)\n"
                "            records_file = find_records_file(byod_root, file_name)\n"
                "        else:\n"
                "            raise ValueError(f'BYOD_PATH must name a .zip or a folder holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise RuntimeError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        if not file_name.lower().endswith('.zip'):\n"
                "            raise ValueError(f'Upload a .zip holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "        extract_zip(payload, byod_root, file_name)\n"
                "        records_file = find_records_file(byod_root, file_name)\n"
                "    records = load_byod_dataset(records_file)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED, base_dir=records_file.parent)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "    byod = {{'file': file_name, 'records_file': records_file.name, 'records': len(records), 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None, 'record_limits': list(byod_record_limits())}}\n"
                "else:\n"
                "    shard_path = fetch_corpus(cache_dir='weights/synthchartnet')\n"
                "    corpus_rows = read_corpus(shard_path)\n"
                "    raw_rows = {{'charts': len(corpus_rows), 'chart_types': dict(collections.Counter(r['chart_type'] for r in corpus_rows))}}\n"
                "    example_row = next(r for r in corpus_rows if r['chart_type'] == 'stacked_bar')\n"
                "    print({{'otsl': example_row['otsl'][:220], 'target': target_from_otsl(example_row['otsl'])[:220]}})\n"
                "    splits = build_sample_dataset(corpus_rows, shard_path, seed=SPLIT_SEED, image_dir='weights/synthchartnet/images')\n"
                "    data_source = f'{{CORPUS_NAME}} — {{CORPUS_RELEASE}}'\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=MIN_RECORDS if name == 'train' else 1) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "chart_types = {{name: manifest['chart_types'] for name, manifest in dataset_manifests.items()}}\n"
                "write_dataset_jsonl(splits['train'], 'outputs/{stem}_train.jsonl')\n"
                "if USE_BYOD:\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'byod': byod}})\n"
                "else:\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'shard_sha256': str(CORPUS_FILE['sha256'])[:16] + '...'}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'charts': manifest['n_records'], 'images': manifest['unique_images'], 'chart_types': manifest['chart_types'], 'table_rows': manifest['table_rows'], 'table_columns': manifest['table_columns'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = splits['train'][0]\n"
                "print({{'example': {{'id': example['id'], 'image': Path(example['image']).name, 'size': example['image_size'], 'chart_type': example['chart_type']}}}})\n"
                "show_chart(example['image'])\n"
                "show_table('target table', example['target_text'])\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in splits['train'][:8]],\n"
                "    'missing image file': [{{**splits['train'][0], 'image': 'work/does-not-exist.png'}}, *splits['train'][1:8]],\n"
                "    'target without a table row': [{{**splits['train'][0], 'target_text': 'TITLE | nothing else'}}, *splits['train'][1:8]],\n"
                "    'too small': splits['train'][:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes, the chart-type counts per split, the chart beside its target table, "
                "and that the splits share no image.\n\n"
                "<details><summary>Check your reasoning</summary>One, or none. The split gives each chart type its share of the "
                "shard's mix, and 0.5 % of 160 is 0.8 charts, so in the recorded Kaggle T4 runs of the previous notebook version "
                "(same seed) the test split held bar 72, pie 73, stacked-bar 14 and line 1. A per-type score on a single line "
                "chart is one observation, not a measurement, and the 14 stacked-bar charts are only a little better: read the "
                "per-type breakdown for bars and pies, and treat the other two types as anecdotes.</details>\n\n"
                "## 5. Extract a table through the inference contract\n\n"
                "The inference contract is exercised as the inference-only tutorial exercised it: a bar chart drawn in code at "
                "800×520 from the five-row table `EXPECTED_TABLE` — the title `Quarterly revenue 2025 (USD millions)`, a y axis "
                "from 0 to 200 with gridlines, four bars for Q1–Q4 with their values printed above them. The cell shows it. It "
                "is a different image family from the SynthChartNet charts, and the adapted model will extract it again in "
                "Section 9. `validate_inputs` applies exactly the checks `extract_table` applies (image sides "
                "`MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE`, `max_new_tokens` in `[1, MAX_NEW_TOKENS]`) and returns an input manifest; a "
                "zero budget is validated too and its rejection recorded as a finding. `extract_table` renders the fixed "
                "instruction as a header above the chart, cuts the composite into at most 2,048 **patches** (16×16-pixel "
                "squares, the encoder's input units), and returns `text` (the **linearised table** exactly as decoded: rows "
                "joined by the `<0x0A>` token, cells by `|`), the parsed `table`, `new_tokens`, a `truncated` flag that is true "
                "when the budget was exhausted, and the model identity. **No score exists.** `evaluation_report` scores it "
                "against the table you drew yourself — verdict `sample-sanity`, plumbing evidence, not a metric. The image "
                "digest depends on the Pillow build's bundled font rendering. On CPU this one extraction takes seconds; on a "
                "GPU, under a second.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *before* or *frozen* number is "
                "never read from the adapted model.\n\n"
                "**Predict before running:** the chart's legend-free y axis is labelled only by its title. Which cells of "
                "`EXPECTED_TABLE` will the model get exactly right, and which header will it write for the value column?"
            ),
            "code": (
                "import csv\n"
                "import gc\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import ImageDraw, ImageFont\n\n"
                "TABLE_MAX_TOKENS = 512  # @param {{type:\"integer\"}}\n"
                "PROGRESS_EVERY = 20  # charts between progress lines in Sections 6-8\n"
                "CHART_TITLE = 'Quarterly revenue 2025 (USD millions)'\n"
                "EXPECTED_TABLE = [['Quarter', 'Revenue'], ['Q1', '120'], ['Q2', '135'], ['Q3', '150'], ['Q4', '180']]\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = DePlotPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "def chart_progress(label, every=PROGRESS_EVERY):\n"
                "    \"\"\"A progress callback for pipe.evaluate: one line every `every` charts and at the end, with the elapsed time.\"\"\"\n"
                "    started = time.perf_counter()\n\n"
                "    def report(done, total):\n"
                "        if done % every == 0 or done == total:\n"
                "            print(f'  {{label}}: {{done}}/{{total}} charts, {{time.perf_counter() - started:.0f}} s')\n"
                "    return report\n\n\n"
                "def bar_chart(width=800, height=520):\n"
                "    \"\"\"Titled bar chart with a labelled y axis, gridlines, x labels and value labels, drawn from EXPECTED_TABLE.\"\"\"\n"
                "    img = Image.new('RGB', (width, height), 'white')\n"
                "    d = ImageDraw.Draw(img)\n"
                "    title_f, tick_f, label_f = ImageFont.load_default(size=24), ImageFont.load_default(size=16), ImageFont.load_default(size=18)\n"
                "    d.text((width / 2 - d.textlength(CHART_TITLE, font=title_f) / 2, 24), CHART_TITLE, fill='black', font=title_f)\n"
                "    x0, y0, x1, y1 = 100, 80, width - 40, height - 80\n"
                "    d.line([(x0, y0), (x0, y1), (x1, y1)], fill='black', width=2)\n"
                "    ymax = 200\n"
                "    for v in range(0, ymax + 1, 50):\n"
                "        y = y1 - (y1 - y0) * v / ymax\n"
                "        d.line([(x0, y), (x1, y)], fill=(200, 200, 200), width=1)\n"
                "        d.text((x0 - 12 - d.textlength(str(v), font=tick_f), y - 9), str(v), fill='black', font=tick_f)\n"
                "    n = len(EXPECTED_TABLE) - 1\n"
                "    slot = (x1 - x0) / n\n"
                "    for i, (label, value) in enumerate(EXPECTED_TABLE[1:]):\n"
                "        bx0 = x0 + slot * i + slot * 0.25\n"
                "        bx1 = bx0 + slot * 0.5\n"
                "        by = y1 - (y1 - y0) * int(value) / ymax\n"
                "        d.rectangle([bx0, by, bx1, y1], fill=(60, 110, 200), outline=(20, 50, 120))\n"
                "        d.text(((bx0 + bx1) / 2 - d.textlength(label, font=label_f) / 2, y1 + 12), label, fill='black', font=label_f)\n"
                "        d.text(((bx0 + bx1) / 2 - d.textlength(value, font=tick_f) / 2, by - 22), value, fill='black', font=tick_f)\n"
                "    d.text((width / 2 - 40, height - 40), 'Quarter', fill='black', font=label_f)\n"
                "    return img\n\n\n"
                "reset_to_pretrained()\n"
                "image = bar_chart()\n"
                "image_name = 'synthetic_bar_chart_800x520.png'\n"
                "image_sha256 = hashlib.sha256(np.asarray(image.convert('RGB')).tobytes()).hexdigest()\n"
                "show_chart(image)\n"
                "ceilings = {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_PATCHES': MAX_PATCHES, 'MAX_NEW_TOKENS': MAX_NEW_TOKENS, 'DEFAULT_MAX_NEW_TOKENS': DEFAULT_MAX_NEW_TOKENS, 'MAX_TARGET_TOKENS': MAX_TARGET_TOKENS, 'MAX_TARGET_CHARS': MAX_TARGET_CHARS, 'DECODING': DECODING, 'INSTRUCTION': INSTRUCTION, 'ROW_SEPARATOR': ROW_SEPARATOR, 'CELL_SEPARATOR': CELL_SEPARATOR, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'MAX_EVAL_RECORDS': MAX_EVAL_RECORDS}}\n"
                "print(ceilings)\n"
                "input_manifest = validate_inputs(image, max_new_tokens=TABLE_MAX_TOKENS, names=[image_name])\n"
                "try:\n"
                "    validate_inputs(image, max_new_tokens=0)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'zero-budget-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'image': image_name, 'rgb_sha256': image_sha256[:16] + '...', 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n"
                "started = time.perf_counter()\n"
                "result = pipe.extract_table(image, max_new_tokens=TABLE_MAX_TOKENS)\n"
                "result_seconds = round(time.perf_counter() - started, 3)\n"
                "print(result['text'])\n"
                "show_table('extracted table', result['text'])\n"
                "checks = {{\n"
                "    'text_is_str': isinstance(result['text'], str),\n"
                "    'budget_respected': result['new_tokens'] <= TABLE_MAX_TOKENS,\n"
                "    'setting_echoed': result['generation']['max_new_tokens'] == TABLE_MAX_TOKENS and result['generation']['do_sample'] is False,\n"
                "    'not_truncated': not result['truncated'],\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'extract_table output failed a sanity check: {{checks}}')\n"
                "frozen_drawn = evaluation_report(result, EXPECTED_TABLE, expected_title=CHART_TITLE, sample_kind='synthetic')\n"
                "print({{'checks': checks, 'seconds': result_seconds, 'new_tokens': result['new_tokens'], 'frozen_drawn_verdict': frozen_drawn['verdict'], 'cell_accuracy': frozen_drawn['metrics'][0]['value'], 'title_match': frozen_drawn['metrics'][1]['value']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the decoded text with its `<0x0A>` row separators, the same table one row per line, "
                "`new_tokens` well under the budget, and that nothing in the output says how sure the model is.\n\n"
                "<details><summary>Check your reasoning</summary>As recorded in the model card, the repository's CPU smoke on "
                "this chart generated 56 tokens: the title and all four quarters and values exactly, and the header "
                "`Quarter | Quarterly revenue` where the reference says `Revenue` — the model took the value column's name from "
                "the title. That one header cell is the miss, so cell accuracy is 0.9 (9 of 10 cells) and the title match 1.0; "
                "the recorded T4 runs gave the same 0.9. A confident, well-formed table with one wrong cell is exactly why a "
                "table is not evidence of its own correctness.</details>\n\n"
                "## 6. Baselines and the frozen model on the test charts\n\n"
                "Three references frame the adaptation, and none looks at the chart. The **empty baseline** emits no table "
                "(the floor: cell accuracy 0). The **header-only baseline** emits, per chart type, the most frequent header "
                "row of the training targets and no data rows — what a system that knows only the layout convention scores. "
                "The **medoid baseline** emits, per chart type, the training table that best matches the other training "
                "tables of its type (the *medoid*: the most typical member of a set). The **frozen model** extracts every test "
                "chart with the budget from Section 5 and is scored by `pipe.evaluate`: mean relaxed **cell accuracy** "
                "(position-wise, so a missing header row or a transposed table shifts every cell), **RNSS** (numbers only, "
                "layout-free), exact-table match and the truncation rate, overall and per chart type. SynthChartNet is not "
                "DePlot's training family and its targets follow the converter's layout rule, so expect the frozen model's cell "
                "accuracy well below its numbers on its own benchmarks; whether it beats the empty table is recorded as "
                "`frozen_beats_empty` rather than assumed. The cell reloads the pretrained model first if an earlier pass "
                "adapted it, and refuses to report an adapted model as frozen. It then shows one test chart of each type beside "
                "its target and the frozen model's table. No per-stage time is recorded for the T4 run (its whole default path "
                "took 4,794 s, fine-tuning 2,290 s of it); on CPU, 160 extractions are estimated at about 20 minutes at 24 threads "
                "and over an hour at 2. A progress line appears every 20 charts.\n\n"
                "**Predict before running:** will the frozen model beat the medoid table on cell accuracy? Will it beat it by "
                "more, or by less, on RNSS?"
            ),
            "code": (
                "reset_to_pretrained()\n"
                "baseline_empty = empty_baseline(test_records)\n"
                "baseline_header = header_only_baseline(train_records, test_records)\n"
                "baseline_medoid = medoid_baseline(train_records, test_records)\n"
                "for baseline in (baseline_empty, baseline_header, baseline_medoid):\n"
                "    print({{'baseline': baseline['baseline'], 'cell_accuracy': round(baseline['cell_accuracy'], 3), 'rnss': round(baseline['rnss'], 3), 'note': baseline['note']}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, max_new_tokens=TABLE_MAX_TOKENS, progress=chart_progress('frozen model, test split'))\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{'cell_accuracy': round(frozen_test['cell_accuracy'], 3), 'rnss': round(frozen_test['rnss'], 3), 'exact_table_match': round(frozen_test['exact_table_match'], 3), 'truncated_rate': round(frozen_test['truncated_rate'], 3)}}, 'n': frozen_test['n'], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'by_chart_type': {{'medoid': baseline_medoid['by_chart_type'], 'frozen': frozen_test['by_chart_type']}}}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n"
                "test_by_id = {{r['id']: r for r in test_records}}\n"
                "shown_ids = []\n"
                "for chart_type in sorted(frozen_test['by_chart_type']):\n"
                "    row = next(r for r in frozen_test['rows'] if r['chart_type'] == chart_type)\n"
                "    shown_ids.append(row['id'])\n"
                "    print(f\"--- {{chart_type}} chart {{row['id']}}: frozen cell accuracy {{row['cell_accuracy']:.3f}}\")\n"
                "    show_chart(test_by_id[row['id']]['image'], width=360)\n"
                "    show_table('target', row['target_text'])\n"
                "    show_table('frozen model', row['prediction'])\n"
                "frozen_beats_empty = frozen_test['cell_accuracy'] > baseline_empty['cell_accuracy']\n"
                "frozen_beats_medoid = frozen_test['cell_accuracy'] > baseline_medoid['cell_accuracy']\n"
                "print({{'frozen_beats_empty': frozen_beats_empty, 'frozen_beats_medoid': frozen_beats_medoid}})"
            ),
        },
        {
            "md": (
                "**What to notice:** `adapted: False`, the progress lines, the gap between the baselines and the frozen model "
                "on each metric, and the charts where the frozen table and the target differ in layout rather than in "
                "numbers.\n\n"
                "<details><summary>Check your reasoning</summary>Yes on both, and by much more on RNSS. In the recorded Kaggle "
                "T4 runs of the previous notebook version the empty, header-only and medoid baselines scored cell accuracy "
                "0.000 / 0.007 / 0.037 and the frozen model 0.160; its RNSS was 0.448 and its exact-table match 0.006. The "
                "gap is far wider on RNSS because the frozen model reads most of the numbers but often lays the table out "
                "differently from the converter's rule (a different header, a missing title row), and position-wise cell "
                "accuracy charges every shifted cell. That gap is what fine-tuning on the converter's targets can close — "
                "which is also why a later gain in cell accuracy may be layout rather than reading.</details>\n\n"
                "## 7. Bounded fine-tuning of the decoder's last blocks\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_DECODER_LAYERS` blocks of the text decoder plus the decoder's "
                "final layer norm — two blocks by default, 18,879,744 of 282,285,696 parameters; the image encoder, every "
                "embedding and the untied output projection stay frozen. Each training chart is one sample: the fixed "
                "instruction is rendered above the chart exactly as `extract_table` renders it, the frozen encoder reads the "
                "composite (recomputed each step without gradients), and the target is the tokenised linearised table "
                "(at most `MAX_TARGET_TOKENS` tokens) with its end-of-sequence token, decoded with **teacher forcing** (the "
                "decoder sees the correct previous tokens, not its own guesses) and scored with the model's own cross-entropy "
                "(padding ignored); AdamW at a fixed learning rate, gradient clipping at 1.0, seeded shuffling and no scheduler. "
                "Epoch 0 records the frozen model's validation metrics; every epoch is scored on the 80 validation charts and "
                "the epoch with the highest **validation** cell accuracy is kept (ties keep the earlier one) — the test split "
                "plays no part in that choice. If no epoch beats the frozen model on validation, the selector keeps epoch 0 and "
                "the adapter reproduces the frozen tables; that outcome is reported, not hidden. A progress line appears every "
                "20 training or validation charts. The three epochs took 2,290 s on the T4 record; on CPU the default "
                "fine-tuning alone is estimated at well over an hour.\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`TRAINABLE_DECODER_LAYERS = 1` in Section 10), it first reloads the pretrained model from the verified "
                "snapshot, so the new training never stacks on the previous one, epoch 0 really is the frozen model, and the "
                "exported adapter holds exactly what this run trained; `pipe.adapt` itself refuses a model that is already "
                "adapted.\n\n"
                "**Predict before running:** will validation cell accuracy rise in every epoch? Which epoch will be kept?"
            ),
            "code": (
                "EPOCHS = 3  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 1e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 4  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_DECODER_LAYERS = 2  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_cell_accuracy': round(entry['val']['cell_accuracy'], 3), 'val_rnss': round(entry['val']['rnss'], 3)}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "def report_charts(entry, started=time.perf_counter()):\n"
                "    if entry['charts'] % PROGRESS_EVERY < (BATCH_SIZE if entry['stage'] == 'train' else 1) or entry['charts'] == entry['of']:\n"
                "        print(f\"  epoch {{entry['epoch']}} {{entry['stage']}}: {{entry['charts']}}/{{entry['of']}} charts, {{time.perf_counter() - started:.0f}} s\")\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_decoder_layers=TRAINABLE_DECODER_LAYERS, progress=report, chart_progress=report_charts)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'training_charts': adapt_result['n_train'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, how the training loss and the validation cell "
                "accuracy move from epoch to epoch, and which epoch is kept.\n\n"
                "<details><summary>Check your reasoning</summary>Not necessarily. In the recorded Kaggle T4 runs of the previous "
                "notebook version the validation cell accuracy rose from 0.123 (epoch 0, the frozen model) to 0.162 at epoch 2, "
                "and epoch 3 did not beat it, so the selector kept epoch 2. The training loss keeps falling while the validation "
                "score levels off: the decoder fits the 360 training tables better than it generalises. Eighty validation charts "
                "give a noisy score, so one epoch's step up or down is not a trend. Had no epoch beaten epoch 0, the rule would "
                "have kept the frozen weights — a legitimate result, not an error.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test charts were never used for training or epoch selection, and no test image appears in the training or "
                "validation splits. The adapted model is scored exactly as the frozen model was in Section 6, and the five "
                "systems — the three baselines, the frozen and the adapted model — are put side by side overall and per chart "
                "type. Read it in this order: **cell accuracy** first (the metric the epoch was selected on), then **RNSS** "
                "(an adaptation that only learns the target layout raises cell accuracy without reading the numbers any better; "
                "RNSS ignores layout), then exact-table match, then the per-type split — stacked-bar and line charts are a small "
                "share of the test split. The cell prints the three deltas and a reading keyed to their signs (a change smaller "
                "than 0.005 counts as flat), and keeps a **run history** for this session, one row per pass through Section 8, so "
                "an experiment can be compared with the default run (Section 10). `adapted_beats_frozen` records whether held-out "
                "cell accuracy rose; it is a cell-accuracy flag, not a verdict on every metric. The charts shown in Section 6 are "
                "shown again with the adapted table. A test split of 160 charts from one seeded draw of one shard gives **no "
                "dispersion estimate**, so the deltas are sample-sanity evidence that the adaptation contract works, not a "
                "benchmark, and a gain on SynthChartNet says nothing about your charts until you measure it there. This cell "
                "scores 240 charts (test and validation), half again as many as Section 6.\n\n"
                "**Predict before running:** if cell accuracy rises, will RNSS rise with it? Will exact-table match?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, max_new_tokens=TABLE_MAX_TOKENS, progress=chart_progress('adapted model, test split'))\n"
                "adapted_val = pipe.evaluate(val_records, max_new_tokens=TABLE_MAX_TOKENS, progress=chart_progress('adapted model, validation split'))\n"
                "comparison = {{\n"
                "    'cell_accuracy': {{'empty': round(baseline_empty['cell_accuracy'], 3), 'header_only': round(baseline_header['cell_accuracy'], 3), 'medoid': round(baseline_medoid['cell_accuracy'], 3), 'frozen': round(frozen_test['cell_accuracy'], 3), 'adapted': round(adapted_test['cell_accuracy'], 3)}},\n"
                "    'rnss': {{'empty': round(baseline_empty['rnss'], 3), 'header_only': round(baseline_header['rnss'], 3), 'medoid': round(baseline_medoid['rnss'], 3), 'frozen': round(frozen_test['rnss'], 3), 'adapted': round(adapted_test['rnss'], 3)}},\n"
                "    'exact_table_match': {{'frozen': round(frozen_test['exact_table_match'], 3), 'adapted': round(adapted_test['exact_table_match'], 3)}},\n"
                "    'delta_vs_frozen': {{'cell_accuracy': round(adapted_test['cell_accuracy'] - frozen_test['cell_accuracy'], 3), 'rnss': round(adapted_test['rnss'] - frozen_test['rnss'], 3), 'exact_table_match': round(adapted_test['exact_table_match'] - frozen_test['exact_table_match'], 3)}},\n"
                "    'by_chart_type': {{chart_type: {{'n': row['n'], 'medoid': baseline_medoid['by_chart_type'][chart_type]['cell_accuracy'], 'frozen': row['cell_accuracy'], 'adapted': adapted_test['by_chart_type'][chart_type]['cell_accuracy']}} for chart_type, row in frozen_test['by_chart_type'].items()}},\n"
                "}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n"
                "adapted_rows = {{r['id']: r for r in adapted_test['rows']}}\n"
                "frozen_rows = {{r['id']: r for r in frozen_test['rows']}}\n"
                "for chart_id in shown_ids:\n"
                "    before, after = frozen_rows[chart_id], adapted_rows[chart_id]\n"
                "    print(f\"--- {{before['chart_type']}} chart {{chart_id}}: cell accuracy {{before['cell_accuracy']:.3f}} frozen -> {{after['cell_accuracy']:.3f}} adapted\")\n"
                "    show_chart(test_by_id[chart_id]['image'], width=360)\n"
                "    show_table('target', before['target_text'])\n"
                "    show_table('frozen model', before['prediction'])\n"
                "    show_table('adapted model', after['prediction'])\n"
                "adapted_beats_frozen = adapted_test['cell_accuracy'] > frozen_test['cell_accuracy']\n"
                "deltas = comparison['delta_vs_frozen']\n\n\n"
                "def direction(delta):\n"
                "    return 'rose' if delta >= 0.005 else 'fell' if delta <= -0.005 else 'stayed flat'\n\n\n"
                "moves = {{metric: direction(adapted_test[metric] - frozen_test[metric]) for metric in ('cell_accuracy', 'rnss', 'exact_table_match')}}\n"
                "reading = f\"cell accuracy {{moves['cell_accuracy']}} ({{deltas['cell_accuracy']:+.3f}}), RNSS {{moves['rnss']}} ({{deltas['rnss']:+.3f}}), exact-table match {{moves['exact_table_match']}} ({{deltas['exact_table_match']:+.3f}}). \"\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    reading += 'The selector kept epoch 0, so the adapted model is the frozen model: no epoch beat it on validation.'\n"
                "elif moves['cell_accuracy'] == 'rose' and moves['rnss'] != 'rose':\n"
                "    reading += 'The gain is in layout - more cells in the expected positions - not in reading more numbers correctly, which RNSS would show.'\n"
                "elif moves['cell_accuracy'] == 'rose':\n"
                "    reading += 'Both rose, so at least part of the gain is in the numbers read, not only in the layout.'\n"
                "elif moves['rnss'] == 'rose':\n"
                "    reading += 'The numbers are read better but the layout is no closer to the targets.'\n"
                "else:\n"
                "    reading += 'Neither cell accuracy nor RNSS rose: this adaptation did not help on these test charts.'\n"
                "print({{'adapted_beats_frozen': adapted_beats_frozen, 'best_epoch': adapt_result['best_epoch']}})\n"
                "print('Reading: ' + reading)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'layers': TRAINABLE_DECODER_LAYERS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'best_epoch': adapt_result['best_epoch'], 'frozen_cell': round(frozen_test['cell_accuracy'], 3), 'adapted_cell': round(adapted_test['cell_accuracy'], 3), 'delta_cell': deltas['cell_accuracy'], 'delta_rnss': deltas['rnss']}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'layers':>6}} {{'epochs':>6}} {{'lr':>8}} {{'best':>4}} {{'frozen':>7}} {{'adapted':>7}} {{'d_cell':>7}} {{'d_rnss':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['layers']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['best_epoch']:>4}} {{h['frozen_cell']:>7.3f}} {{h['adapted_cell']:>7.3f}} {{h['delta_cell']:>+7.3f}} {{h['delta_rnss']:>+7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'chart_types': chart_types,\n"
                "    'max_new_tokens': TABLE_MAX_TOKENS,\n"
                "    'baselines': {{'empty': baseline_empty, 'header_only': baseline_header, 'medoid': baseline_medoid}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'frozen_beats_empty': frozen_beats_empty,\n"
                "    'frozen_beats_medoid': frozen_beats_medoid,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'reading': reading,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "    'adapted_beats_frozen': adapted_beats_frozen,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the printed reading, the per-type line, the charts with three tables each, "
                "and the run history.\n\n"
                "<details><summary>Check your reasoning</summary>Not in the recorded runs. On the Kaggle T4 runs of the previous "
                "notebook version cell accuracy rose 0.160 → 0.181 (+0.021) while RNSS stayed flat (0.448 → 0.447) and exact-table "
                "match fell from 0.006 to 0.000 (one chart of 160 to none). `adapted_beats_frozen` was `True`, but read with RNSS "
                "that is the *layout-learning* pattern: the adapted decoder writes tables shaped more like the converter's "
                "targets, so more cells land in the expected positions, while the set of numbers it reads is no better. So a "
                "`True` flag here does not mean the model reads charts better. Your run's reading line states your own numbers; "
                "write them down before Section 10.</details>\n\n"
                "## 9. Re-extract the drawn chart, export the adapter and reload it\n\n"
                "The drawn bar chart from Section 5 is extracted again by the adapted model and scored against the table you "
                "drew — a different image family from the SynthChartNet charts it was tuned on, and one with a title and a "
                "header the SynthChartNet targets never carry, so this is a small look at whether the adaptation changed the "
                "model's behaviour *outside* its sample (one chart of evidence, not a measurement; a different table here is a "
                "finding to record, not a failure). Both tables are written as CSV.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the decoder's last two blocks and its final layer norm by "
                "default, about 76 MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact format, the base "
                "model id and revision, the digest of the base `model.safetensors`, the tensor names, the file size and SHA-256, "
                "the training configuration, the kept epoch and the epoch history (OUT8). An **adapter** is only the changed "
                "tensors; it is meaningless without the pinned base. `DePlotPipeline.from_artifact` re-verifies the base "
                "snapshot, checks the artifact manifest, its digest and its exact tensor set **before** deserialising, refuses "
                "any tensor that is not a decoder tensor, and overlays the tensors onto a freshly loaded base — a new object from "
                "files, not the in-memory model (VER2). The cell checks for identical tables on eight test charts (**reload "
                "parity**, VER4) and stops with an explanation if they differ. Under BYOD `result.json` records your upload in "
                "place of the SynthChartNet corpus block.\n\n"
                "**Predict before running:** will the adapted model change the drawn chart's table, and will reload parity hold?"
            ),
            "code": (
                "adapted_result = pipe.extract_table(image, max_new_tokens=TABLE_MAX_TOKENS)\n"
                "adapted_drawn = evaluation_report(adapted_result, EXPECTED_TABLE, expected_title=CHART_TITLE, sample_kind='synthetic')\n"
                "show_table('frozen model', result['text'])\n"
                "show_table('adapted model', adapted_result['text'])\n"
                "print({{'drawn_chart_cell_accuracy': {{'frozen': frozen_drawn['metrics'][0]['value'], 'adapted': adapted_drawn['metrics'][0]['value']}}}})\n"
                "with open('outputs/{stem}_table.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['model', 'row', 'cells'])\n"
                "    for label, extracted in (('frozen', result), ('adapted', adapted_result)):\n"
                "        for index, row in enumerate(extracted['table']['rows']):\n"
                "            writer.writerow([label, index, ' | '.join(row)])\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'best_epoch': artifact_manifest['adapter']['best_epoch']}})\n\n"
                "reloaded = DePlotPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "before = [r['text'] for r in pipe.predict(test_records[:8], max_new_tokens=TABLE_MAX_TOKENS)]\n"
                "after = [r['text'] for r in reloaded.predict(test_records[:8], max_new_tokens=TABLE_MAX_TOKENS)]\n"
                "parity = {{'identical_tables': sum(a == b for a, b in zip(before, after, strict=True)), 'of': len(before)}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "reloaded = None  # free the second copy of the model before any re-run\n"
                "gc.collect()\n"
                "if parity['identical_tables'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the model that was evaluated in Section 8. Re-run from Section 7 (it reloads the pretrained model before adapting), or restart the session and choose Run all.')\n\n"
                "weight_entry = next(entry for entry in MANIFEST['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'SafeTensors, loaded in float32, digest-verified', 'weight_sha256': weight_entry['sha256']}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'release': CORPUS_RELEASE, 'license': CORPUS_LICENSE, 'file': CORPUS_FILE, 'sample_charts': SAMPLE_CHARTS, 'target_rule': 'bar, pie, stacked_bar transposed; line kept; TITLE row first'}},\n"
                "    'byod': byod,\n"
                "    'splits': disjoint,\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'drawn_chart': {{'name': image_name, 'size': list(image.size), 'rgb_sha256': image_sha256, 'expected_table': EXPECTED_TABLE, 'expected_title': CHART_TITLE}}, 'frozen': {{k: result[k] for k in ('text', 'new_tokens', 'truncated')}}, 'frozen_report': frozen_drawn, 'adapted': {{k: adapted_result[k] for k in ('text', 'new_tokens', 'truncated')}}, 'adapted_report': adapted_drawn, 'seconds': result_seconds}},\n"
                "    'adaptation': {{'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'learning_rate': LEARNING_RATE, 'epochs': EPOCHS, 'trainable_decoder_layers': TRAINABLE_DECODER_LAYERS, 'batch_size': BATCH_SIZE}},\n"
                "    'comparison': comparison,\n"
                "    'reading': reading,\n"
                "    'frozen_beats_empty': frozen_beats_empty,\n"
                "    'frozen_beats_medoid': frozen_beats_medoid,\n"
                "    'adapted_beats_frozen': adapted_beats_frozen,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** whether the drawn chart's table changed, the artifact's tensor count, size and kept epoch, and "
        "the reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>In the recorded Kaggle T4 runs of the previous notebook version the "
        "drawn chart's cell accuracy stayed 0.9 after adaptation — training on SynthChartNet's untitled tables did not "
        "break this one titled chart, which is one chart of evidence, not a measurement. The artifact held 29 tensors (two "
        "blocks of 14 plus the final layer norm, 75,522,608 bytes) and reload parity was 8/8: the exported adapter is the "
        "model that was evaluated. Parity holds because the adaptation started from the pretrained base, so the adapter "
        "carries every tensor that differs from it.</details>\n\n"
        "## 10. Your turn — change one thing: train one decoder block instead of two\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It retrains, so it takes about as long as Section 7 did "
        "(Section 7 alone took 2,290 s on the T4 record with two blocks; Sections 8 and 9 come on top; hours on CPU).\n\n"
        "1. **Predict:** with `TRAINABLE_DECODER_LAYERS = 1` (half the trainable parameters), how big will the adapter be, "
        "will held-out cell accuracy and RNSS move more or less than in your default run, and will reload parity hold? Write "
        "your guesses next to the default run's row in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `TRAINABLE_DECODER_LAYERS = 1`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation cell accuracy again (in the recorded T4 runs "
        "0.123), not the adapted one — the sign that the model was reset; read the trainable-parameter count. In Section 8, "
        "compare the two rows of the run history and the reading line. In Section 9, read the tensor count, the bytes and "
        "the reload parity.\n"
        "5. **Explain:** in one or two sentences, what did halving the trainable blocks change in the adapter and in the "
        "held-out deltas, and does the difference between the two runs exceed what one seeded split of 160 charts can "
        "resolve?\n\n"
        "<details><summary>Check your reasoning</summary>Some answers are fixed by the design: the adapter holds 15 tensors "
        "(one block of 14 plus the final layer norm) and 9,440,256 trainable parameters, 37,762,904 bytes — about half the default's 75.5 MB (measured in a local CPU check with the pinned weights) — "
        "and reload parity holds because Section 7 started from the pretrained model, so the adapter carries every changed "
        "tensor. (Before this notebook reset the model, the same experiment trained on top of the first run, exported only "
        "the last block, and failed reload parity.) The held-out deltas are *your* result: read the two run-history rows "
        "side by side, check RNSS as well as cell accuracy, and remember that with no dispersion estimate a difference of a "
        "few thousandths between the two runs is not evidence that one setting is better.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen model is a plot-to-table translator scored on charts of a family it was not fine-tuned on, beside three "
        "baselines that never look at the chart, and a bounded fine-tuning of the decoder's last two blocks on a few hundred "
        "charts is then scored on a held-out test split — overall and per chart type — with an adapter that reloads to "
        "identical tables. That is the claim: the adaptation contract works end to end on a real labelled chart corpus, and "
        "the numbers it produces are read against the baselines and the frozen model rather than in isolation. Whether "
        "held-out cell accuracy rose is recorded as `adapted_beats_frozen`, not assumed, and Section 8 prints what the "
        "three deltas together say.\n\n"
        "Cell accuracy is position-wise, so part of any gain can be the model learning the converter's layout — no header row "
        "for a single unnamed series, the transposed stacked bars — rather than reading values better; RNSS, which ignores "
        "layout, is the check on that, and in the recorded runs it did not move. The test split is 160 charts from one "
        "seeded draw of one shard, the validation split that picks the epoch is 80, stacked-bar and line charts are a small "
        "share of both, and SynthChartNet carries some label noise. **The model generates a table for any image**: an image "
        "that is not a chart produces a confident fabrication rather than an empty result, and `truncated` is the only "
        "structural flag you get. Fine-tuning on a narrow sample can also erode the model elsewhere; the drawn chart "
        "re-extracted in Section 9 is one chart of evidence about that, not a measurement.\n\n"
        "Three things to carry to real data. **Baselines first:** the empty, header-only and medoid tables on *your* charts "
        "are the numbers to read before any model's, per chart type. **Layout is part of the target:** decide your table "
        "orientation and header rule once, from what the frozen model emits, and convert every label to it — a transposed "
        "target scores as a miss on every cell. **Leakage:** keep every record of a chart in one split (the contract does "
        "this) and split by source document when your charts come from few reports.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real labelled chart "
        "corpus, validate the demonstrated dataset contract without leakage, execute the inference contract and a bounded "
        "fine-tuning, evaluate against three trivial baselines and the frozen model on a held-out split, and emit the shown "
        "machine-readable artifacts — without the repository being reachable. It does **not** establish benchmark "
        "superiority, accuracy on any other chart population, or production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one thing; note the numbers you "
        "want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **Fewer trainable blocks:** Section 10.\n"
        "- **A higher learning rate:** set `LEARNING_RATE = 1e-4` in Section 7, select Section 7 and choose **Run after**. "
        "What happens to the training loss and to the validation cell accuracy, and which epoch does the selector keep?\n"
        "- **More epochs:** set `EPOCHS = 5` in Section 7, select Section 7 and choose **Run after**. Does validation cell "
        "accuracy keep rising after the default's kept epoch, and does RNSS follow it?\n"
        "- **Another split:** change `SPLIT_SEED` in Section 4, select Section 4 and choose **Run after**. How far do the "
        "frozen and adapted scores move with a different draw of 160 test charts — more or less than the default run's "
        "delta?\n"
        "- **Unlabelled bars:** in Section 5 delete the line in `bar_chart` that draws the value above each bar, then run "
        "Section 5 only. How many of the four values does the model still recover from the bar heights and the axis?\n"
        "- **Your own charts:** BYOD (Section 4, then **Run after**). Before the adapted number, how do the three baselines "
        "and the frozen model score on your charts, per chart type?\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **The run is very slow, or the session ends before Section 9.** On CPU the default path takes hours (Prerequisites). "
        "Switch to a GPU runtime (**Runtime → Change runtime type**) and choose **Run all** again; the progress lines in "
        "Sections 6–8 show how far a long stage has got.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory (the model is "
        "1.13 GB in float32, and Section 9 briefly holds two copies). Restart the session and choose **Run all**; on CPU, "
        "close other notebooks first. A CUDA out-of-memory error in Section 7 can be avoided with `BATCH_SIZE = 2`.\n"
        "- **Out of disk, or a download stops.** The locked install, the 1.13 GB checkpoint and the 516 MB shard need several "
        "GB of free space. Start a fresh runtime, or delete `dimer_isolated_env/` and `weights/` from an earlier attempt.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses it "
        "rather than continuing. Run the cell again; never edit the manifest or the corpus pins.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split with too few or too many records (12 "
        "to 2,502 records, one per chart image), no or several records files, an image path that does not exist relative to "
        "the records file, a target with no table row or over 512 characters, a duplicate id, a zip over the member or size "
        "limit, or a member outside the upload folder. Fix the zip and run Section 4 with **Run after** again. An empty or "
        "cancelled upload, or a runtime without the Colab upload dialog, asks you to choose a file or set `BYOD_PATH`.\n"
        "- **Section 8 reads \"The selector kept epoch 0\" or \"did not help\".** Not an error: under these settings no "
        "adaptation beat the frozen model on validation, or the kept epoch did not beat it on test. Read the epoch history in "
        "Section 7; the export and reload in Section 9 still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** CPU and GPU arithmetic differ, and because decoding is "
        "autoregressive one different token changes the rest of a table; differences of a few thousandths between a T4 and a "
        "CPU run are expected. Larger differences on the default settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Linearised table:** a table written as one string — `TITLE | <title>` first, rows joined by the `<0x0A>` token "
        "(a newline written as a byte token) and cells by ` | `. It is what DePlot generates and what the targets use.\n"
        "- **OTSL:** the corpus's table markup, one token per cell; the carried converter turns it into a linearised table.\n"
        "- **Rendered header:** the fixed instruction drawn as text above the chart, so the model reads the prompt as pixels "
        "(the Pix2Struct VQA convention).\n"
        "- **Patches:** the 16×16-pixel squares the encoder reads; a chart is resized to at most 2,048 of them.\n"
        "- **Greedy decoding / token budget:** generating each next token as the single most likely one, up to "
        "`max_new_tokens`; `truncated` says the budget ran out. Reproducible, not a quality guarantee.\n"
        "- **Cell accuracy (relaxed, position-wise):** the share of target cells matched by the predicted cell at the same "
        "row and column, numbers within 5 %.\n"
        "- **RNSS:** relative number set similarity — how closely the set of numbers in the prediction matches the target's, "
        "ignoring where they are.\n"
        "- **Exact-table match:** the prediction equals the target table cell for cell.\n"
        "- **Baseline (empty / header-only / medoid):** systems that never see the chart, showing what any useful model must "
        "beat; the medoid is the most typical training table of a chart type.\n"
        "- **Fine-tuning / trainable blocks:** further training on labelled examples; only the named decoder blocks may "
        "change, the rest stay frozen.\n"
        "- **Teacher forcing:** during training the decoder is fed the correct previous tokens of the target, not its own "
        "predictions.\n"
        "- **Epoch / validation selection:** one pass over the training charts; the epoch kept is the one with the highest "
        "validation cell accuracy (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** charts used to train, to choose the epoch, and to report the final result "
        "once; split by chart image so no image is in two splits.\n"
        "- **Adapter / reload parity:** the saved trained tensors, and the check that a pipeline rebuilt from them and the "
        "pinned base gives the same tables.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- The task: from ___ to ___. On the test charts the medoid baseline reached a cell accuracy of ___, the pretrained "
        "model ___ and the adapted model ___ (kept epoch ___).\n"
        "- RNSS moved from ___ to ___, so the change in cell accuracy reflects ___ (layout / reading / both).\n"
        "- One failure mode I saw in the charts shown: ___. The chart types with too few test charts to judge were ___.\n"
        "- Training one block instead of two (Section 10) changed ___; the difference between the runs is / is not larger "
        "than one seeded split can resolve, because ___.\n"
        "- Before trusting this adaptation on my own charts I would measure ___ on ___, with the baselines first.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/deplot-chart-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/deplot-chart-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/deplot-chart-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model (Google, Apache-2.0): https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/google-research/pix2struct\n"
        "- DePlot: One-shot visual language reasoning by plot-to-table translation (Liu et al., 2022): https://arxiv.org/abs/2212.10505\n"
        "- Pix2Struct: Screenshot Parsing as Pretraining for Visual Language Understanding (Lee et al., ICML 2023): https://arxiv.org/abs/2210.03347\n"
        "- ChartQA: A Benchmark for Question Answering about Charts with Visual and Logical Reasoning (Masry et al., 2022): https://arxiv.org/abs/2203.10244\n"
        "- SynthChartNet (docling-project, CDLA-Permissive-2.0): https://huggingface.co/datasets/docling-project/SynthChartNet\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
